# tenabot/analytics/pdf_generation_service.py
import os
import time
import logging
from django.conf import settings
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer,
    ListFlowable,
    ListItem,
)
from reportlab.lib.units import inch
from reportlab.lib import colors

logger = logging.getLogger(__name__)

def generate_harvard_pdf(resume_data, telegram_id):
    """Generate a clean Harvard-style resume PDF using ReportLab."""
    try:
        output_dir = os.path.join(settings.MEDIA_ROOT, "generated_resumes")
        os.makedirs(output_dir, exist_ok=True)

        filename_base = f"resume_{telegram_id}_{int(time.time())}.pdf"
        pdf_path = os.path.join(output_dir, filename_base)

        logger.info(f"🧾 [PDF] Generating Harvard-style resume for user {telegram_id}")
        logger.info(f"🗂 Saving to {pdf_path}")

        # --- Document setup ---
        doc = SimpleDocTemplate(pdf_path, pagesize=A4, rightMargin=72, leftMargin=72)
        styles = getSampleStyleSheet()
        styles.add(ParagraphStyle(name="SectionTitle", fontSize=13, leading=16, spaceAfter=6, textColor=colors.darkblue))
        styles.add(ParagraphStyle(name="JobTitle", fontSize=11, leading=14, spaceAfter=4, textColor=colors.HexColor("#222222")))
        story = []

        # --- Header ---
        title = resume_data.get("position_inferred", "Professional Resume")
        story.append(Paragraph(f"<b>{title}</b>", styles["Title"]))
        story.append(Spacer(1, 0.2 * inch))

        # --- Contact Info ---
        story.append(Paragraph(f"<b>Phone:</b> {resume_data.get('phone', 'N/A')}", styles["Normal"]))
        story.append(Paragraph(f"<b>Email:</b> {resume_data.get('email', 'N/A')}", styles["Normal"]))
        story.append(Paragraph(f"<b>LinkedIn:</b> {resume_data.get('linkedin', 'N/A')}", styles["Normal"]))
        story.append(Spacer(1, 0.3 * inch))

        # --- Core Values ---
        core_values = resume_data.get("core_values", [])
        if core_values:
            story.append(Paragraph("Core Values", styles["SectionTitle"]))
            story.append(ListFlowable([ListItem(Paragraph(v, styles["Normal"])) for v in core_values], bulletType="bullet"))
            story.append(Spacer(1, 0.25 * inch))

        # --- Skills ---
        skills = resume_data.get("skills", [])
        if skills:
            story.append(Paragraph("Skills", styles["SectionTitle"]))
            story.append(ListFlowable([ListItem(Paragraph(s, styles["Normal"])) for s in skills], bulletType="bullet"))
            story.append(Spacer(1, 0.25 * inch))

        # --- Work Experience ---
        work_history = resume_data.get("work_history", [])
        if work_history:
            story.append(Paragraph("Work Experience", styles["SectionTitle"]))
            for job in work_history:
                title_line = f"<b>{job.get('title', 'N/A')}</b> — {job.get('company', 'N/A')}"
                story.append(Paragraph(title_line, styles["JobTitle"]))
                story.append(Paragraph(f"{job.get('start_date', '')} - {job.get('end_date', '')}", styles["Italic"]))
                if job.get("summary"):
                    story.append(Paragraph(job["summary"], styles["Normal"]))
                story.append(Spacer(1, 0.15 * inch))

        # --- Education ---
        education = resume_data.get("full_education", [])
        if education:
            story.append(Paragraph("Education", styles["SectionTitle"]))
            for edu in education:
                edu_line = (
                    f"{edu.get('degree', '')} in {edu.get('field_of_study', '')} "
                    f"from {edu.get('institution', '')} ({edu.get('graduation_date', '')})"
                )
                story.append(Paragraph(edu_line, styles["Normal"]))
                story.append(Spacer(1, 0.1 * inch))

        # --- Footer ---
        story.append(Spacer(1, 0.3 * inch))
        story.append(Paragraph(
            "Generated by <b>Tenabot AI Resume Assistant</b> using Gemini AI.",
            styles["Italic"]
        ))

        doc.build(story)
        logger.info(f"✅ [PDF] Successfully created Harvard PDF for {telegram_id}")
        return pdf_path

    except Exception as e:
        logger.error(f"💥 [PDF] Failed to generate Harvard PDF for {telegram_id}: {e}", exc_info=True)
        return None
